import keyMirror from 'keymirror';

export default keyMirror({
  SELECT_OVERTIME: null,
  SELECT_OVERTIME_ERROR: null,
  RECIEVE_OVERTIMES: null,
  RECIEVE_OVERTIMES_ERROR: null,
  RECIEVE_OVERTIMES_AND_SELECT: null,
  SAVE_OVERTIME: null,
  SAVE_OVERTIME_ERROR: null,
  DELETE_OVERTIME: null,
  DELETE_OVERTIME_ERROR: null,

  SELECT_USER: null,
  SELECT_USER_ERROR: null,
  RECIEVE_USERS: null,
  RECIEVE_USERS_ERROR: null,
  RECIEVE_USERS_AND_SELECT: null,
  SAVE_USER: null,
  SAVE_USER_ERROR: null,
  DELETE_USER: null,
  DELETE_USER_ERROR: null
});
